project:
  type: website
  output-dir: docs

website:
  title: "Teemu Säilynoja"
  navbar:
    left:
      - href: index.qmd
        text: Home
      #- about.qmd
      - href: cv.qmd
        text: CV
    right:
      - icon: linkedin
        #text: LinkedIn
        href: https://www.linkedin.com/in/teemu-sailynoja/
      - icon: github
        #text: Github
        href: https://github.com/TeemuSailynoja
      - icon: envelope-at
        #text: Email
        href: mailto:teemu.sailynoja@gmail.com

format:
  html:
    theme:
      dark:
        - darkly
        - theme-dark.scss
      light: 
        - flatly
        - theme-light.scss
    css: styles.css
    toc: true
    fontsize: "16pt"
    max-width: "74ch"
    linkcolor: "#bf616a"


# babelquarto:
#   languagelinks: navbar
#   languagecodes:
#   - name: fi
#     text: "Suomeksi"
#   - name: en
#     text: "In English"
#   mainlanguage: 'en'
#   languages: ['fi']
# title-fi: Teemu Säilynoja
# author-fi: Teemu Säilynoja
# lang: en
